---
# für Windows-Hosts, welche keiner Domain zugehören.
- name: Windwos Playbook
  hosts: Windows-Server

- task:
  - name: Install AD Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result

- name: Create new forest
  win_domain:
    dns_domain_name: test-domain.com
    safe_mode_password: Test123
  register: result


- name: reboot after creation
  win_reboot:
    msg: "server config in progress, rebooting..."
  when: result.reboot_required


    